WIP: convert server code to aws sdk v2
I thought maybe I'd get lucky as I noticed the README before this change
for Kinesis didn't work. It still doesn't work :)

Besides figuring out why autoconfigure/collector-kinesis instructions
don't work, there's also an expiration case to sort out. Help wanted!

```
2019-06-15 20:14:03.577  INFO 23289 --- [0000000000-0000] s.a.k.r.p.PrefetchRecordsPublisher       : ShardId shardId-000000000000: records threw ExpiredIteratorException - restarting after greatest seqNum passed to customer

software.amazon.awssdk.services.kinesis.model.ExpiredIteratorException: Iterator expired. The iterator was created at time Sat Jun 15 11:00:34 UTC 2019 while right now it is Sat Jun 15 12:14:03 UTC 2019 which is further in the future than the tolerated delay of 300000 milliseconds. (Service: Kinesis, Status Code: 400, Request ID: e91fc2d4-7f9f-4b46-bc61-219ff5be0a68)
```